export const ALL_PRODUCT_REQUEST = 'ALL_PRODUCT_REQUEST'
export const ALL_PRODUCT_SUCCES = 'ALL_PRODUCT_SUCCES'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const ALL_PRODUCT_FAIL = 'ALL_PRODUCT_FAIL'
