export const ALL_PRODUCT_REQUEST = 'ALL_PRODUCT_REQUEST'
export const ALL_PRODUCT_SUCCES = 'ALL_PRODUCT_SUCCES'
export const ALL_PRODUCT_FAIL = 'ALL_PRODUCT_SUCCES'

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST'
export const PRODUCT_DETAIL_SUCCES = 'PRODUCT_DETAIL_SUCCES'
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
